[#14] orm이용한 스마트캠퍼스 크롤링
DaITssu/daitssu-crawl pull request #23
Opened 2023-08-31 06:55 UTC by NokboongI

## Issue

- Resolves #14 

## Description

- 이전 psycopg2을 이용해 db에 바로 insert하는 코드에서 orm을 이용하는 코드로 수정
- orm을 한번도 사용해본 적이 없어 제대로 한 것인지는 확실치 않음

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-09-02 04:51 UTC, k0000k commented on smart_campus.py
> +from django.db import models
사용하신 라이브러리는 django 라이브러리의 db 모듈입니다. django 서버를 개발하는 것이라면 해당 라이브러리를 사용하시는게 편하시겠지만, 현재 상황에서는 크롤링한 데이터를 DB에 Insert 하기만 하면 되며 라이브러리 통일을 위해 sqlalchemy 사용하시는게 더 적절할 것 같습니다. #22 과 #17 참고하시면 도움이 되실 것 같습니다.

2023-09-02 04:52 UTC, k0000k commented on smart_campus.py
> +                    pass
pass를 사용하신 이유가 있으실까요?

2023-09-02 04:54 UTC, k0000k requested changes
코멘트 확인하시고 수정 부탁드립니다~~

2023-09-02 04:55 UTC, k0000k commented
또한 지금 main에 있는 smart_compus.py와 컨플릭트 발생했습니다. 로직 먼저 수정하신뒤 충돌도 해소 하시면 다시 리뷰 하도록 하겠습니다! 충돌 잡는거 어려우시면 도와드리겠습니다 :)

2023-09-02 05:20 UTC, NokboongI commented on smart_campus.py
> +                    pass
출결상태를 받아올때 새로 추가된 출결상태가 아니면 데이터를 또 추가하지 않아야 한다고 생각해서 pass 사용하면 그냥 넘어간다고 해서 continue와 비슷하다 생각해 사용했습니다

2023-09-02 06:18 UTC, k0000k commented on smart_campus.py
> +                    pass
pass는 보통 해당 블럭내에서 아무것도 하지 않을 때 또는 베이스 코드 작성시 아직 미구현인 부분을 채울 때 사용합니다. 또한 pass는 반복문 수행에 아무런 영향을 끼치지 않고, 현재 코드에서는 pass 아래에 아무 로직이 없으므로 그냥 삭제하는게 가독성 측면에서 좋을 것 같습니다.

2023-09-02 08:16 UTC, NokboongI commented on smart_campus.py
> +                    pass
넵 알겠습니다

2023-09-02 09:59 UTC, NokboongI commented
일단 수정은 했는데 지금 수정한 코드도 충돌이 발생할까요?

2023-09-02 10:00 UTC, NokboongI commented
충돌은 어떻게 해결해야 하는걸까요..?

2023-09-02 10:01 UTC, k0000k commented
제가 디코로 따로 연락드릴게요~!

2023-09-03 12:06 UTC, k0000k approved these changes

2023-09-03 12:07 UTC, k0000k commented
확인하고 approve 했습니다. 특별히 문제 있는 부분 없으시면 머지해주세요!

2023-09-03 12:36 UTC, merged