Feat/ci cd
DaITssu/daitssu-crawl pull request #47
Opened 2023-10-20 01:17 UTC by HwanGonJang

## Issue

크롤러 서버 배포하기

## Description

크롤러 서버를 람다에서 ecs로 배포합니다.
배포 url: https://crawler.daitssu.com/docs

## Check List

- [x]  PR 제목을 커밋 규칙에 맞게 작성
- [x]  PR에 해당되는 Issue를 연결 완료
- [x]  적절한 라벨 설정
- [x]  작업한 사람 모두를 Assign
- [x]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [x]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot
![image](https://github.com/DaITssu/daitssu-crawl/assets/33739448/7bf1868e-27c2-43f0-9752-b8899730d48a)

2023-10-20 01:17 UTC, HwanGonJang commented
깃허브 액션은 pr 병합 후에 돌아서 테스트하지 못했습니다. 병합하고 안되면 말씀해주세요. 배포는 수동으로 완료했고 코드에 문제가 없다면 액션도 잘 돌아갈겁니다

2023-10-21 09:38 UTC, kkanggu requested changes
감사합니다.

2023-10-21 09:38 UTC, kkanggu commented on .github/workflows/deploy-ecs.yml
> +
이 부분은 테스트 목적으로 수정하였기에, main 브랜치로 수정해야 합니다.

2023-10-25 09:23 UTC, k0000k approved these changes
확인했습니다!

2023-10-25 09:23 UTC, k0000k commented on .github/workflows/deploy-ecs.yml
> +
저 부분만 main으로 변경하고 머지하면 될까요?

2023-10-26 04:54 UTC, HwanGonJang commented on .github/workflows/deploy-ecs.yml
> +
```
  branches:
    - main
```

요렇게 하심 될거에요

2023-10-27 11:16 UTC, kkanggu commented on .github/workflows/deploy-ecs.yml
> +
본 PR에 해당 내용 미리 반영 부탁드립니다.

2023-10-27 15:28 UTC, k0000k commented on .github/workflows/deploy-ecs.yml
> +
반영했습니다! 이외 추가로 변경해야하는 부분 없으면 머지하겠습니다.

2023-10-28 10:39 UTC, kkanggu approved these changes

2023-10-28 12:04 UTC, merged